# coding: utf-8

"""
    aind-metadata-service

     ## aind-metadata-service  Service to pull data from example backend.  

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_metadata_service_async_client.models.output_directory import OutputDirectory

class TestOutputDirectory(unittest.TestCase):
    """OutputDirectory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputDirectory:
        """Test OutputDirectory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputDirectory`
        """
        model = OutputDirectory()
        if include_optional:
            return OutputDirectory(
                anyof_schema_1_validator = '',
                anyof_schema_2_validator = '',
                actual_instance = None,
                any_of_schemas = [
                    ''
                    ]
            )
        else:
            return OutputDirectory(
        )
        """

    def testOutputDirectory(self):
        """Test OutputDirectory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
