services:
  aind-metadata-service-local:
    build: ./aind-metadata-service-server
    ports:
      - "5000:80"
    expose:
      - "5000"
    depends_on:
      - labtracks
      - mgi
      - smartsheet
      - sharepoint
      - tars
      - dataverse
      - redis
    env_file: "env/webapp_v1.env"
  labtracks:
    image: "ghcr.io/allenneuraldynamics/aind-labtracks-service-server:0.5.0"
    env_file: "env/labtracks.env"
  mgi:
    image: "ghcr.io/allenneuraldynamics/aind-mgi-service-server:0.1.2"
  smartsheet:
    image: "ghcr.io/allenneuraldynamics/aind-smartsheet-service-server:1.1.0"
    env_file: "env/smartsheet.env"
  sharepoint:
    image: "ghcr.io/allenneuraldynamics/aind-sharepoint-service-server:0.3.0"
    env_file: "env/sharepoint.env"
  tars:
    image: "ghcr.io/allenneuraldynamics/aind-tars-service-server:0.1.5"
    env_file: "env/tars.env"
  dataverse:
    image: "ghcr.io/allenneuraldynamics/aind-dataverse-service-server:0.4.0"
    env_file: "env/dataverse.env"
  redis:
    image: "redis:latest"
