services:
  aind-metadata-service-local:
    build: ./aind-metadata-service-server
    ports:
      - "5000:80"
    expose:
      - "5000"
    depends_on:
      - labtracks
  labtracks:
    image: "ghcr.io/allenneuraldynamics/aind-labtracks-service-server:0.2.3"
    env_file: "env/labtracks.env"
