services:
  aind-metadata-service-local:
    build: ./aind-metadata-service-server
    ports:
      - "5000:80"
    expose:
      - "5000"
    depends_on:
      - labtracks
      - mgi
      - slims
      - smartsheet
    volumes:
      - ./aind-metadata-service-server/src:/app/src
    env_file: "env/webapp.env"
  labtracks:
    image: "ghcr.io/allenneuraldynamics/aind-labtracks-service-server:0.2.4"
    env_file: "env/labtracks.env"
  mgi:
    image: "ghcr.io/allenneuraldynamics/aind-mgi-service-server:0.1.2"
  smartsheet:
    image: "ghcr.io/allenneuraldynamics/aind-smartsheet-service-server:0.2.1"
    env_file: "env/smartsheet.env"
  slims:
    image: "ghcr.io/allenneuraldynamics/aind-slims-service-server:0.2.4"
    env_file: "env/slims.env"
  sharepoint:
    image: "ghcr.io/allenneuraldynamics/aind-sharepoint-service-server:0.0.11"
    env_file: "env/sharepoint.env"
  redis:
    image: "redis:latest"
