services:
  aind-metadata-service-local:
    build: ./aind-metadata-service-server
    ports:
      - "5000:80"
    expose:
      - "5000"
    depends_on:
      - labtracks
      - mgi
      - slims
      - smartsheet
      - sharepoint
      - tars
      - session_json
      - redis
      - aind_metadata_service_v1
    env_file: "env/webapp.env"
  labtracks:
    image: "ghcr.io/allenneuraldynamics/aind-labtracks-service-server:0.3.0"
    env_file: "env/labtracks.env"
  mgi:
    image: "ghcr.io/allenneuraldynamics/aind-mgi-service-server:0.1.2"
  smartsheet:
    image: "ghcr.io/allenneuraldynamics/aind-smartsheet-service-server:0.2.2"
    env_file: "env/smartsheet.env"
  slims:
    image: "ghcr.io/allenneuraldynamics/aind-slims-service-server:0.3.2"
    env_file: "env/slims.env"
  sharepoint:
    image: "ghcr.io/allenneuraldynamics/aind-sharepoint-service-server:0.1.3"
    env_file: "env/sharepoint.env"
  tars:
    image: "ghcr.io/allenneuraldynamics/aind-tars-service-server:0.1.3"
    env_file: "env/tars.env"
  session_json:
    image: "ghcr.io/allenneuraldynamics/aind-session-json-service-server:0.1.3"
  aind_metadata_service_v1:
    image: "ghcr.io/allenneuraldynamics/aind-metadata-service-server:1.1.4"
    depends_on:
      - labtracks
      - mgi
      - slims
      - smartsheet
      - sharepoint
      - tars
      - session_json
      - redis
    env_file: "env/webapp_v1.env"
  redis:
    image: "redis:latest"