services:
  fastapi:
    build: .
    ports:
      - "5000:5000"
      - "58350:58350"
    depends_on:
      - redis
    env_file: "env/webapp.env"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
