from pydantic import BaseModel, Field, Extra
from typing import Optional
from datetime import datetime


class ExcelSheetRow(BaseModel, extra=Extra.allow):
    s_perfusion_date: Optional[datetime] = Field(default=None, alias=' Perfusion Date')
    hashtag: Optional[int] = Field(default=None, alias='#')
    actual_perfusion_date: Optional[datetime] = Field(default=None, alias='Actual Perfusion Date')
    age_injected: Optional[int] = Field(default=None, alias='Age Injected')
    age_at_perfusion: Optional[int] = Field(default=None, alias='Age at perfusion')
    age_of_injection: Optional[int] = Field(default=None, alias='Age of Injection')
    age_of_perfusion: Optional[int] = Field(default=None, alias='Age of Perfusion')
    calb2_creert2_ai166: Optional[str] = Field(default=None, alias='Calb2-CreERT2;Ai166')
    dob: Optional[datetime] = Field(default=None, alias='DOB')
    delipidation: Optional[str] = Field(default=None, alias='Delipidation')
    dose: Optional[int] = Field(default=None, alias='Dose')
    gelation: Optional[str] = Field(default=None, alias='Gelation')
    gross_anatomical_observations: Optional[str] = Field(default=None, alias='Gross Anatomical Observations')
    gross_anatomical_observations_pre_processing: Optional[str] = Field(default=None, alias='Gross Anatomical Observations (pre-processing)')
    gross_anatomy_notes_pre_processing: Optional[str] = Field(default=None, alias='Gross Anatomy Notes (pre-processing)')
    gross_anatomy_observations_pre_processing: Optional[str] = Field(default=None, alias='Gross Anatomy Observations (pre-processing)')
    gross_anatomical_observation: Optional[str] = Field(default=None, alias='Gross anatomical observation')
    injection_requested: Optional[str] = Field(default=None, alias='Injection Requested?')
    las_notes: Optional[str] = Field(default=None, alias='LAS Notes')
    las_notes_1: Optional[str] = Field(default=None, alias='LAS Notes.1')
    las_perfusion_dissection_notes: Optional[str] = Field(default=None, alias='LAS Perfusion/Dissection Notes')
    las_injection_notes: Optional[str] = Field(default=None, alias='LAS injection Notes')
    mouse_id: Optional[str] = Field(default=None, alias='Mouse ID')
    my_notes: Optional[str] = Field(default=None, alias='My notes')
    notes: Optional[str] = Field(default=None, alias='Notes')
    pedigree: Optional[str] = Field(default=None, alias='Pedigree')
    perfusion_date: Optional[datetime] = Field(default=None, alias='Perfusion Date')
    perfusion_requested: Optional[str] = Field(default=None, alias='Perfusion Requested?')
    perfusion_type: Optional[str] = Field(default=None, alias='Perfusion Type')
    ro_injection_date: Optional[datetime] = Field(default=None, alias='RO Injection Date')
    sex: Optional[str] = Field(default=None, alias='Sex')
    staining: Optional[str] = Field(default=None, alias='Staining')
    status: Optional[str] = Field(default=None, alias='Status')
    tam_injection_first_day: Optional[str] = Field(default=None, alias='TAM injection (first day)')
    tam_injection_last_day: Optional[str] = Field(default=None, alias='TAM injection (last day)')
    tissue_processing_notes: Optional[str] = Field(default=None, alias='Tissue Processing Notes')
    titer: Optional[str] = Field(default=None, alias='Titer')
    unnamed_0: Optional[str] = Field(default=None, alias='Unnamed: 0')
    unnamed_1: Optional[str] = Field(default=None, alias='Unnamed: 1')
    unnamed_10: Optional[str] = Field(default=None, alias='Unnamed: 10')
    unnamed_11: Optional[str] = Field(default=None, alias='Unnamed: 11')
    unnamed_12: Optional[str] = Field(default=None, alias='Unnamed: 12')
    unnamed_13: Optional[str] = Field(default=None, alias='Unnamed: 13')
    unnamed_14: Optional[str] = Field(default=None, alias='Unnamed: 14')
    unnamed_15: Optional[str] = Field(default=None, alias='Unnamed: 15')
    unnamed_16: Optional[str] = Field(default=None, alias='Unnamed: 16')
    unnamed_17: Optional[str] = Field(default=None, alias='Unnamed: 17')
    unnamed_18: Optional[str] = Field(default=None, alias='Unnamed: 18')
    unnamed_19: Optional[str] = Field(default=None, alias='Unnamed: 19')
    unnamed_2: Optional[str] = Field(default=None, alias='Unnamed: 2')
    unnamed_20: Optional[str] = Field(default=None, alias='Unnamed: 20')
    unnamed_21: Optional[str] = Field(default=None, alias='Unnamed: 21')
    unnamed_22: Optional[str] = Field(default=None, alias='Unnamed: 22')
    unnamed_23: Optional[str] = Field(default=None, alias='Unnamed: 23')
    unnamed_3: Optional[str] = Field(default=None, alias='Unnamed: 3')
    unnamed_4: Optional[str] = Field(default=None, alias='Unnamed: 4')
    unnamed_5: Optional[str] = Field(default=None, alias='Unnamed: 5')
    unnamed_6: Optional[str] = Field(default=None, alias='Unnamed: 6')
    unnamed_7: Optional[str] = Field(default=None, alias='Unnamed: 7')
    unnamed_8: Optional[str] = Field(default=None, alias='Unnamed: 8')
    unnamed_9: Optional[str] = Field(default=None, alias='Unnamed: 9')
    vehicle: Optional[str] = Field(default=None, alias='Vehicle')
    virus: Optional[str] = Field(default=None, alias='Virus')
    virus_id: Optional[str] = Field(default=None, alias='Virus ID')
    volume_injected: Optional[str] = Field(default=None, alias='Volume Injected')
