# coding: utf-8

"""
    aind-metadata-service

     ## aind-metadata-service  Service to pull data from example backend.  

    The version of the OpenAPI document: 1.1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_metadata_service_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.TestCase):
    """HealthcheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthcheckApi()

    def tearDown(self) -> None:
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        Perform a Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
