# coding: utf-8

"""
    aind-metadata-service

     ## aind-metadata-service  Service to pull data from example backend.  

    The version of the OpenAPI document: 2.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_metadata_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_procedures(self) -> None:
        """Test case for get_procedures

        Get Procedures
        """
        pass

    def test_get_subject(self) -> None:
        """Test case for get_subject

        Get Subject
        """
        pass

    def test_get_v1_bergamo_session(self) -> None:
        """Test case for get_v1_bergamo_session

        Get V1 Bergamo Session
        """
        pass

    def test_get_v1_funding(self) -> None:
        """Test case for get_v1_funding

        Get V1 Funding
        """
        pass

    def test_get_v1_injection_materials(self) -> None:
        """Test case for get_v1_injection_materials

        Get V1 Injection Materials
        """
        pass

    def test_get_v1_instrument(self) -> None:
        """Test case for get_v1_instrument

        Get V1 Instrument
        """
        pass

    def test_get_v1_intended_measurements(self) -> None:
        """Test case for get_v1_intended_measurements

        Get V1 Intended Measurements
        """
        pass

    def test_get_v1_mgi_allele(self) -> None:
        """Test case for get_v1_mgi_allele

        Get V1 Mgi Allele
        """
        pass

    def test_get_v1_perfusions(self) -> None:
        """Test case for get_v1_perfusions

        Get V1 Perfusions
        """
        pass

    def test_get_v1_procedures(self) -> None:
        """Test case for get_v1_procedures

        Get V1 Procedures
        """
        pass

    def test_get_v1_project_names(self) -> None:
        """Test case for get_v1_project_names

        Get V1 Project Names
        """
        pass

    def test_get_v1_protocols(self) -> None:
        """Test case for get_v1_protocols

        Get V1 Protocols
        """
        pass

    def test_get_v1_rig(self) -> None:
        """Test case for get_v1_rig

        Get V1 Rig
        """
        pass

    def test_get_v1_slims_workflow(self) -> None:
        """Test case for get_v1_slims_workflow

        Get V1 Slims Workflow
        """
        pass

    def test_get_v1_subject(self) -> None:
        """Test case for get_v1_subject

        Get V1 Subject
        """
        pass

    def test_index(self) -> None:
        """Test case for index

        Index
        """
        pass


if __name__ == '__main__':
    unittest.main()
