# coding: utf-8

"""
    aind-metadata-service

     ## aind-metadata-service  Service to pull data from example backend.  

    The version of the OpenAPI document: 1.1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_metadata_service_client.models.hit_rate_trials010 import HitRateTrials010

class TestHitRateTrials010(unittest.TestCase):
    """HitRateTrials010 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HitRateTrials010:
        """Test HitRateTrials010
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HitRateTrials010`
        """
        model = HitRateTrials010()
        if include_optional:
            return HitRateTrials010(
            )
        else:
            return HitRateTrials010(
        )
        """

    def testHitRateTrials010(self):
        """Test HitRateTrials010"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
