class NSBList2023:
    """Class to contain helpful info to parse the 2023 SharePoint List"""

    class StringParserHelper:
        """Enum class for SharePoint's response strings"""

        # Not really why, but some response fields return 'Select...'
        SELECT_STR = "Select..."
        PROCEDURE_TYPE_SPLITTER = "+"
        WITH_HEADPOST = " (with Headpost)"
        BURR_TYPE_SPLITTER = "&"

    class ProcedureType:
        """Enum class for 2023 SharePoint's Specific Procedure Type"""

        STEREOTAXIC_INJECTION = "Stereotaxic Injection"
        ISI_INJECTION = "ISI-guided Injection"
        FIBER_OPTIC_IMPLANT = "Fiber Optic Implant"
        INJECTION = "Injection"
        INJ = "INJ"
        WITH_HEADPOST = "with Headpost"
        WHC_NP = "WHC NP"
        HP_ONLY = "HP Only"
        HP_TRANSCRANIAL = "HP Transcranial"
        VISUAL_CTX_2P = "Visual Ctx 2P"
        FRONTAL_CTX_2P = "Frontal Ctx 2P"
        MOTOR_CTX = "Motor Ctx"
        VISUAL_CTX_NP = "Visual Ctx NP"
        INJECTION_FIBER_IMPLANT = "Injection+Fiber Optic Implant"

    class BurrHoleType:
        """Enum class for 2023 SharePoint's BurrHole Procedures"""

        INJECTION = "Injection"
        FIBER_IMPLANT = "Fiber Implant"
        INJECTION_FIBER_IMPLANT = "Injection & Fiber Implant"

    class InjectionType:
        """Enum class of Injection Types"""

        IONTO = "Iontophoresis"
        NANOJECT = "Nanoject (Pressure)"

    class HeadFrameType:
        """Enum class for Headframe Types"""

        VISUAL_CTX = "Visual Ctx"
        FRONTAL_CTX = "Frontal Ctx"
        MOTOR_CTX = "Motor Ctx"
        WHC_2P = "WHC 2P"
        WHC_NP = "WHC NP"
        AI_STRAIGHT_BAR = "AI Straight bar"
        OTHER = "Other"

    class WellType:
        """Enum class for Well Types"""

        NO_WELL = "No Well"
        CAM = "Scientifica (CAM)"
        MESOSCOPE = "Mesoscope"
        NEUROPIXEL = "Neuropixel"
        WHC_2P = "WHC 2P"
        WHC_NP = "WHC NP"
        OTHER = "Other"

    class SurgeryOrder:
        """Enum class for Initial/FollowUp classifiers"""

        INITIAL = "Initial Surgery"
        SECOND = "Follow up Surgery"

    class ListField:
        """Enum class for fields in List Item object response"""

        FILE_SYSTEM_OBJECT_TYPE = "FileSystemObjectType"
        ID = "Id"
        SERVER_REDIRECTED_EMBED_URI = "ServerRedirectedEmbedUri"
        SERVER_REDIRECTED_EMBED_URL = "ServerRedirectedEmbedUrl"
        TITLE = "Title"
        PI_ID = "PIId"
        PI_STRING_ID = "PIStringId"
        LAB_TRACKS_REQUESTOR = "LabTracks_x0020_Requestor"
        PROJECT_ID_TE = "Project_x0020_ID_x0020__x0028_te"
        IACUC_PROTOCOL = "IACUC_x0020_Protocol_x0020__x002"
        DATE_RANGE_START = "DateRangeStart"
        LIGHT_CYCLE = "Light_x0020_Cycle"
        LIMS_REQUIRED = "LIMs_x0020_Required"
        LIMS_PROJECT_CODE = "Lims_x0020_Project_x0020_Code"
        LIM_STASKFLOW1 = "LIMStaskflow1"
        TEST_ID = "Test1Id"
        TEST_STRING_ID = "Test1StringId"
        DATE_OF_SURGERY = "Date_x0020_of_x0020_Surgery"
        HP_WORK_STATION = "HpWorkStation"
        TEST_1ST_ROUND_ID = "TEST_x0020_1st_x0020_Round_x0020Id"
        TEST_1ST_ROUND_STRING_ID = "TEST_x0020_1st_x0020_Round_x0020StringId"
        DATE1ST_INJECTION = "Date1stInjection"
        WORK_STATION1ST_INJECTION = "WorkStation1stInjection"
        LAB_TRACKS_GROUP = "LabTracks_x0020_Group"
        LAB_TRACKS_ID = "LabTracks_x0020_ID1"
        PEDIGREE_NAME = "PedigreeName"
        SEX = "Sex"
        DATE_OF_BIRTH = "Date_x0020_of_x0020_Birth"
        WEIGHT_BEFORE_SURGER = "Weight_x0020_before_x0020_Surger"
        WEIGHT_AFTER_SURGERY = "Weight_x0020_after_x0020_Surgery"
        ISO_ON = "Iso_x0020_On"
        HP_ISO_LEVEL = "HPIsoLevel"
        HP_RECOVERY = "HPRecovery"
        FIRST_INJECTION_WEIGHT_BEFOR = "FirstInjectionWeightBefor"
        FIRST_INJECTION_WEIGHT_AFTER = "FirstInjectionWeightAfter"
        FIRST_INJECTION_ISO_DURATION = "FirstInjectionIsoDuration"
        ROUND1_INJ_ISOLEVEL = "Round1InjIsolevel"
        FIRST_INJ_RECOVERY = "FirstInjRecovery"
        BREG2_LAMB = "Breg2Lamb"
        SURGERY_STATUS = "SurgeryStatus"
        LONG_REQUESTOR_COMMENTS = "LongRequestorComments"
        PROCEDURE_SLOTS = "Procedure_x0020_Slots"
        PROCEDURE_FAMILY = "Procedure_x0020_Family"
        PROCEDURE_T2 = "Procedure_x0020_T2"
        PROCEDURE = "Procedure"
        HEADPOST = "Headpost"
        HEADPOST_TYPE = "HeadpostType"
        CRANIOTOMY_TYPE = "CraniotomyType"
        IMPLANT_ID_COVERSLIP_TYPE = "ImplantIDCoverslipType"
        BURR_HOLE_1 = "Burr_x0020_hole_x0020_1"
        INJ1_VIRUS_STRAIN_RT = "Inj1VirusStrain_rt"
        BURR1_VIRUS_BIOSAFTE = "Burr1_x0020_Virus_x0020_Biosafte"
        INJ1_STORAGE_LOCATION = "Inj1StorageLocation"
        INJ1_TYPE = "Inj1Type"
        VIRUS_HEMISPHERE = "Virus_x0020_Hemisphere"
        INJ1_ANGLE_V2 = "Inj1Angle_v2"
        INJ1VOLPERDEPTH = "inj1volperdepth"
        INJ1_CURRENT = "Inj1Current"
        INJ1_ALTERNATING_TIME = "Inj1AlternatingTime"
        RET_SETTING0 = "retSetting0"
        INJ1_IONTO_TIME = "Inj1IontoTime"
        VIRUS_M_L = "Virus_x0020_M_x002f_L"
        VIRUS_A_P = "Virus_x0020_A_x002f_P"
        VIRUS_D_V = "Virus_x0020_D_x002f_V"
        FIBER_IMPLANT1_LENGT = "Fiber_x0020_Implant1_x0020_Lengt"
        FIBER_IMPLANT1_DV = "FiberImplant1DV"
        BURR_HOLE_2 = "Burr_x0020_hole_x0020_2"
        INJ2_VIRUS_STRAIN_RT = "Inj2VirusStrain_rt"
        BURR2_VIRUS_BIOSAFTE = "Burr2_x0020_Virus_x0020_Biosafte"
        INJ2_STORAGE_LOCATION = "Inj2StorageLocation"
        INJ2_TYPE = "Inj2Type"
        HEMISPHERE2ND_INJ = "Hemisphere2ndInj"
        INJ2_ANGLE_V2 = "Inj2Angle_v2"
        INJ2VOLPERDEPTH = "inj2volperdepth"
        INJ2_CURRENT = "Inj2Current"
        INJ2_ALTERNATING_TIME = "Inj2AlternatingTime"
        RET_SETTING1 = "retSetting1"
        INJ2_IONTO_TIME = "Inj2IontoTime"
        ML2ND_INJ = "ML2ndInj"
        AP2ND_INJ = "AP2ndInj"
        DV2ND_INJ = "DV2ndInj"
        FIBER_IMPLANT2_LENGT = "Fiber_x0020_Implant2_x0020_Lengt"
        FIBER_IMPLANT2_DV = "FiberImplant2DV"
        BURR_HOLE_3 = "Burr_x0020_hole_x0020_3"
        INJ_VIRUS_STRAIN_RT = "InjVirusStrain_rt"
        BURR3_VIRUS_BIOSAFTE = "Burr3_x0020_Virus_x0020_Biosafet"
        INJ3_STORAGE_LOCATION = "Inj3StorageLocation"
        INJ3_TYPE = "Inj3Type"
        BURR3_HEMISPHERE = "Burr_x0020_3_x0020_Hemisphere"
        BURR3_ANGLE = "Burr_x0020_3_x0020_Angle"
        BURR3_AP = "Burr3_x0020_A_x002f_P"
        BURR3_ML = "Burr3_x0020_M_x002f_L"
        BURR3_DV = "Burr3_x0020_D_x002f_V"
        INJ3VOLPERDEPTH = "inj3volperdepth"
        INJ3_CURRENT = "Inj3Current"
        INJ3_ALTERNATING_TIME = "Inj3AlternatingTime"
        INJ3_RET_SETTING = "Inj3retSetting"
        INJ3_IONTO_TIME = "Inj3IontoTime"
        FIBER_IMPLANT3_LENGT = "Fiber_x0020_Implant3_x0020_Lengt"
        FIBER_IMPLANT3_D = "Fiber_x0020_Implant3_x0020_D_x00"
        BURR_HOLE_4 = "Burr_x0020_hole_x0020_4"
        INJ4_VIRUS_STRAIN_RT = "Inj4VirusStrain_rt"
        BURR4_VIRUS_BIOSAFTE = "Burr4_x0020_Virus_x0020_Biosafte"
        INJ4_STORAGE_LOCATION = "Inj4StorageLocation"
        INJ4_TYPE = "Inj4Type"
        BURR4_HEMISPHERE = "Burr_x0020_4_x0020_Hemisphere"
        BURR4_ANGLE = "Burr_x0020_4_x0020_Angle"
        INJ4VOLPERDEPTH = "Inj4volperdepth"
        INJ4_CURRENT = "Inj4Current"
        INJ4_ALTERNATING_TIME = "Inj4AlternatingTime"
        INJ4_RET_SETTING = "Inj4retSetting"
        INJ4_IONTO_TIME = "Inj4IontoTime"
        BURR4_AP = "Burr4_x0020_A_x002f_P"
        BURR4_ML = "Burr4_x0020_M_x002f_L"
        BURR4_DV = "Burr4_x0020_D_x002f_V"
        FIBER_IMPLANT4_LENGT = "Fiber_x0020_Implant4_x0020_Lengt"
        FIBER_IMPLANT4_D = "Fiber_x0020_Implant4_x0020_D_x00"
        COM_DUROTOMY = "ComDurotomy"
        COM_SWELLING = "ComSwelling"
        COM_SINUSBLEED = "ComSinusbleed"
        COM_DAMAGE = "ComDamage"
        COM_WINDOW = "ComWindow"
        COM_COPLANAR = "ComCoplanar"
        CONTUSION = "Contusion"
        IONTO_NUMBER_INJ1 = "IontoNumberInj1"
        NANOJECT_NUMBER_INJ10 = "NanojectNumberInj10"
        IONTO_NUMBER_INJ2 = "IontoNumberInj2"
        NANOJECT_NUMBER_INJ2 = "NanojectNumberInj2"
        HP_SURGEON_COMMENTS = "HPSurgeonComments"
        AGE_AT_INJECTION = "Age_x0020_at_x0020_Injection"
        CONTENT_TYPE_ID = "ContentTypeId"
        COMPLIANCE_ASSET_ID = "ComplianceAssetId"
        CREATED = "Created"
        ID2 = "ID"
        MODIFIED = "Modified"
        AUTHOR_ID = "AuthorId"
        EDITOR_ID = "EditorId"
        ODATA_UI_VERSION_STRING = "OData__UIVersionString"
        ATTACHMENTS = "Attachments"
        GUID = "GUID"
        BURR1_DURING = "Burr1_x0020_Perform_x0020_During"
        BURR2_DURING = "Burr2_x0020_Perform_x0020_During"
        BURR3_DURING = "Burr3_x0020_Perform_x0020_During"
        BURR4_DURING = "Burr4_x0020_Perform_x0020_During"
        HEADPOST_DURING = "Headpost_x0020_Perform_x0020_Dur"
        CRANIOTOMY_DURING = "Craniotomy_x0020_Perform_x0020_D"
