name: Tag and publish
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from file
        id: getversion
        run: |
          pkg_name=$(grep -P 'version = \{attr = .*\}' pyproject.toml | grep -oP '\w+.__version__')
          init_file="./src/${pkg_name//.__version__}/__init__.py"
          new_tag=$(grep -Po '__version__ = "\K.*?(?=")' $init_file)
          echo "::set-output name=version::$new_tag"
      - name: Bump tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.getversion.outputs.version }}
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from file
        id: getversion
        run: |
          pkg_name=$(grep -P 'version = \{attr = .*\}' pyproject.toml | grep -oP '\w+.__version__')
          init_file="./src/${pkg_name//.__version__}/__init__.py"
          new_tag=$(grep -Po '__version__ = "\K.*?(?=")' $init_file)
          echo "::set-output name=version::$new_tag"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          push: true
          tags: |
            ghcr.io/alleninstitute/aind-metadata-service:${{ steps.getversion.outputs.version }}
            ghcr.io/alleninstitute/aind-metadata-service:latest
