name: Tag and publish v1
on:
  push:
    branches:
      - v1

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.output_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: output_version
        run: |
          ls .
          init_file="./aind-metadata-service-server/src/aind_metadata_service_server/__init__.py"
          pkg_version=$(grep -Po '[0-9]+\.[0-9]+\.[0-9]+' "$init_file")
          echo "new_version=$pkg_version" >> "$GITHUB_OUTPUT"
  publish_server:
    runs-on: ubuntu-latest
    needs: [get_version]
    defaults:
      run:
        working-directory: ./aind-metadata-service-server
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest changes
        run: git pull origin v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./aind-metadata-service-server
          push: true
          tags: |
            ghcr.io/allenneuraldynamics/aind-metadata-service-server:${{ needs.get_version.outputs.new_version }}
