name: Run checks in dev

on:
  pull_request:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: | 
        python -m pip install -e .[dev]
    - name: Run linter checks
      run: flake8 . && interrogate --verbose .
    - name: Run tests and coverage
      run: coverage run -m unittest discover && coverage report
